export type Colors = {
  white: string
  black: string
  // Grays
  grey5: string
  grey10: string
  grey20: string
  grey30: string
  grey50: string
  grey70: string
  grey80: string
  grey90: string
  // bes
  blue10: string
  blue20: string
  blue30: string
  blue40: string
  blue50: string
  blue70: string
  blue90: string
  // Purples
  violet10: string
  violet20: string
  violet30: string
  violet50: string
  violet70: string
  violet90: string
  // onges
  orange10: string
  orange20: string
  orange30: string
  orange50: string
  orange70: string
  orange90: string
  // rs
  red10: string
  red20: string
  red30: string
  red50: string
  red70: string
  red90: string
  // pmary
  primary10: string
  primary20: string
  primary30: string
  primary40: string
  primary50: string
  primary70: string
  primary90: string
  // Misc
  primary: string
  danger: string
  success: string
  warning: string
}
